version: '3.9'
services:

  ms-sql-server-an:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
      MSSQL_PID: Express
    ports:
      - 1443:1443
    volumes:
      - "appdb_an:/var/opt/mssql/data"
    networks:
      - app

  wordofthedayapp:
    build:
      dockerfile: WordOfTheDay.AnaliticsMicroservice.Api/Dockerfile
    image: wordoftheday_an
    environment:
      DbServer: "ms-sql-server"
      DbPort: "1443"
      DbUser: "sa"
      Password: "Password123!"
      Database: "appdb"
    ports:
      - 7001:70
    restart: on-failure
    depends_on:
      - ms-sql-server-an
    networks:
      - app

volumes:
  appdb_an:

networks:
  app:
    external:
      name: wordofthedayapp_app

