version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    volumes:
      - "~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/"
      - "~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
      MSSQL_PID: Express
    ports:
      - 1443:1443
    volumes:
      - "app2-db:/var/opt/mssql/data"
  wordofthedayapp:
    build:
      dockerfile: WordOfTheDay.AnaliticsMicroservice.Api/Dockerfile
    image: wordofthedayms
    ports:
      - 7001:70
volumes:
  app2-db: